### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by gabcollet** [JaeSeoKim/badge42#75]
Hello, I'm from 42 Quebec and when I try to log on the badge42 website I receive this message : Application error: a client-side exception has occurred (see the browser console for more information).

The browser console show me : 
![image](https://user-images.githubusercontent.com/79753678/161596951-730dad00-8e3c-4892-aa62-f9264ce4fe6f.png)

I've try with firefox and chrome.

I'm not sure if it have something to do with the fact that our school does'nt have coalitions yet since it's a relatively new one.

Thanks!

**Comment by JaeSeoKim** [comment]
I fixed this error. Please check it out! 08488f6d0d5200f3b601a9b76b5bc3184ff3127b

**Comment by gabcollet** [comment]
Thanks for the quick answer. I still have the same application error but now console say : 
![image](https://user-images.githubusercontent.com/79753678/161756172-00e84775-6e02-4f44-928c-15c751dcaa1b.png)

Just to be extra sure I also try on both Ubuntu and Windows.

**Comment by JaeSeoKim** [comment]
Can I know the email address of the account I signed up for?

**Comment by JaeSeoKim** [comment]
I need to check how the internal data is, so I just need 42 Intra email.

**Comment by gabcollet** [comment]
Sure my 42 email is : gcollet@student.42quebec.com

**Comment by JaeSeoKim** [comment]
This time, corrected the error...! Please check it out!

**Comment by gabcollet** [comment]
![image](https://user-images.githubusercontent.com/79753678/161791416-fec28d83-0db8-4c89-a1b8-61390d897050.png)

Sry still doesnt work. I also try with mmondell@student.42quebec.com from the same school. It doesn't work for him either.

**Comment by JaeSeoKim** [comment]
I accidentally misdistributed the code used for testing, causing an issue overall;;
I revised the commit again after rollback, so please check it.

**Comment by JaeSeoKim** [comment]
@all-contributors please add @gabcollet  for bug

**Comment by gabcollet** [comment]
Looks like it's working now, nice job!
